### ISSUE TITLE
server image request

### ISSUE THREAD

**Issue by ihaveamac** [916253/Kurisu#38]
We're looking for a new server image when we rename "3DS Hacking" to "**Nintendo Homebrew**"! We are including the Wii U and Nintendo Switch. The new server image should follow a few rules, and we have some ideas too if you are not sure.

* contains the face buttons (ABXY) or D-pad of 3DS and Wii U (and Switch if you like)
* a general symbol for homebrew on Nintendo systems
* your own idea!

Limitations:
* no immediately identifiable Nintendo-owned logos
* is not specific to one system
* no shitpost or meme submissions

Server image must be at least 128×128. 256×256 or higher preferred. Remember the image will be cropped to a circle in most cases, so design it around this.

Please post your Discord username alongside the image, preferably in the format of DiscordTag#0000 (e.g. ihaveahax#1684).

_The Enrichment Center is required to remind you that the winner will be baked, and then there will be cake._

**Comment by ihaveamac** [comment]
some useful images:

http://www.gamestop.com/gs/images/content-pdp/New_Nintendo_3DS/Nintendo_New3DS_Open_.jpg
http://1u88jj3r4db2x4txp44yqfj1.wpengine.netdna-cdn.com/wp-content/uploads/2015/08/New-3DS.jpg
http://www.gamestop.com/gs/images/content-pdp/New_Nintendo_3DS/NewN3DSXL_black.jpg
http://cdn1.expertreviews.co.uk/sites/expertreviews/files/5/19/new_3ds_vs_new_3ds_xl_0_0.png?itok=UMoZ_akE

http://www.chopstixz.net/wp-content/uploads/2012/09/Wii-U_GamePad_white.jpg
http://www.mariowiki.com/images/f/f4/Blackcontroller_big.png

http://blogs-images.forbes.com/erikkain/files/2016/12/NintendoSwitch_hardware.0.0.jpg
https://cdn3.vox-cdn.com/uploads/chorus_asset/file/7312781/NintendoSwitch_hardware2.0.jpg

**Comment by lucario1001** [comment]
http://i.imgur.com/kTRe0uc.png

Lucario101#0216

**Comment by ihaveamac** [comment]
you should probably put the image in as a preview.
```markdown
![alt text](image-url)
```

**Comment by ErmanSayin** [comment]
![nintendo-homebrew-logo](https://cloud.githubusercontent.com/assets/5402062/22598113/a1db1ff4-ea32-11e6-8ec9-182e5ea84188.png)

erman1337#8528

**Comment by whimee** [comment]
![Homebrew](https://cdn.discordapp.com/attachments/247267886228307969/247288303668297728/HB-browser-icon.png)

I also have a square icon if you need it.

Sticki#9563

**Comment by BlackSpark644** [comment]
![Logo](https://static.blackspark.pw/NintendoHomebrew.png)

The SVG is available [here](https://static.blackspark.pw/NintendoHomebrew.svg).

[Here's how it looks in Discord](https://streamable.com/3y4el)

BlackSpark#9089

**Comment by Cody090909** [comment]
![pic](https://cloud.githubusercontent.com/assets/25541217/22615159/cc98dbbe-ea4b-11e6-9350-435532982901.png)
Cody090909#6599

**Comment by WafflesYem** [comment]
![icon](http://i.imgur.com/NlpZ3Zd.png)
Tried my best to copy the homebrew theme
Waffles#8363

**Comment by Ahris** [comment]
I designed a logo in Swapnote's style! The blue of the house is a reference to the 3DS launcher. :-)
![](https://68.media.tumblr.com/fc434f7517ed5118fb8edff5ed8c6d38/tumblr_oky25mufv71uacl8mo1_400.png)
Ahris#7652

**Comment by 916253** [comment]
# Announcement: Limited time left for submissions!

As we pass a week of the contest being open, it is time to start wrapping up design ideas. Submissions will remain open until some time on monday, at which point they will be closed, and all submitted images will be reviewed. Good luck!

**Comment by 466gaming** [comment]
![](http://i.imgur.com/yFdjk8U.jpg)
466#8617

**Comment by HexOverflow** [comment]
![nintendohomebrew](https://cloud.githubusercontent.com/assets/24927193/22848460/ab558548-efc2-11e6-917a-ce1b4958d9c3.png)
nosebleed#0109

**Comment by HexOverflow** [comment]
Also here's a darker icon
![nintendohomebrew](https://cloud.githubusercontent.com/assets/24927193/22848567/793f543e-efc3-11e6-9e3f-8fccfaae33dd.png)

**Comment by ihaveamac** [comment]
the icon has been selected and will be revealed soon.

**Comment by maorninja** [comment]
@Cody090909 Since that image isn't being used on the server, can I have it?

**Comment by Cody090909** [comment]
Sorry, but I am probably going to use it.
