### ISSUE TITLE
feature suggestion: .err / .ninerr merge

### ISSUE THREAD

**Issue by sirocyl** [916253/Kurisu#63]
valid .err codes and valid .ninerr codes do not intersect; err codes are four bytes hex, ninerr codes are in ###-#### or ##### format, for Wii U/3DS and Wii, respectively, where # is a digit [0-9].

**Comment by T3CHNOLOG1C** [comment]
This ^

**Comment by sirocyl** [comment]
Seems to have been or begun to merge as of 997a7360f6ba229292ad0a438f8a2637663d00f4. Closing.
